@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDcxMTI0NTV9.AhHp_QqCa9HG6WOqqLc2slYOHRUwJSDigCkuEEOl3xE

@domain = http://localhost:3000

### User create (sign up)
POST {{ domain }}/users
Content-Type: application/json

{
  "first_name": "Dani",
  "last_name": "Zeeeee",
  "user_name": "Danizee",
  "email": "Dani@gmail.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": ""
}

### Sessions create (login)
GET {{ domain }}/sessions
Content-Type: application/json

{
  "email": "meghan@gmail.com",
  "password": "password"
}

###################################### USERS
### User show
GET {{ domain }}/users/me
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### User update
PATCH {{ domain }}/users/me
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "image_url": "http://placeimg.com/640/480/people?t=1646424933414"
}

### User delete
DELETE {{ domain }}/users/me
Content-Type: application/json
Authorization: Bearer {{ jwt }}

################################### PRODUCTS
### Product index
GET {{ domain }}/products

### Product create
POST {{ domain }}/products
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Test Product",
  "description": "Cleans things",
  "category": "green",
  "image_url": "",
  "price": 4,
  "ingredients": "water, soap"
}

### Product show
GET {{ domain }}/products/9
Content-Type: application/json

######################################### PRODUCT ALTERNATIVES
### ProductAlternatives create
POST {{ domain }}/product_alternatives
Content-Type: application/json

{
  "standard_product_id": "21",
  "green_product_id": "22"
}

### ProductAlternatives destroy
DELETE {{ domain }}/product_alternatives/2
Content-Type: application/json

######################################## REVIEWS
### Review create
POST {{ domain }}/reviews
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "product_id": 10,
  "title": "Test review",
  "image_url": "",
  "body": "I love this product!!",
  "star_rating": 5
}

### Review update
PATCH {{ domain }}/reviews/7
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "image_url": "https://i5.walmartimages.com/asr/3c5910f8-4f34-4979-b014-b34e416c14ff_1.3f6241a35df3e30eb77a60d144a043a4.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF"
}

### Review destroy
DELETE {{ domain }}/reviews/7
Content-Type: application/json
Authorization: Bearer {{ jwt }}