@jwt = 

@domain = http://localhost:3000

### User create (sign up)
POST {{ domain }}/users
Content-Type: application/json

{
  "first_name": "Meghan",
  "last_name": "Scherzer",
  "user_name": "meghan44",
  "email": "meghan@gmail.com",
  "password_digest": "password",
  "image_url": ""
}

### Sessions create (login)
GET {{ domain }}/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password_digest": "password"
}