@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDY4Njc5ODh9.NjQyfQAASxj7YR2mCt3Z_iBT325rTTBA9XVbxOi7vWM

@domain = http://localhost:3000

### User create (sign up)
POST {{ domain }}/users
Content-Type: application/json

{
  "first_name": "Isabel",
  "last_name": "Thedog",
  "user_name": "imthedawg14",
  "email": "thedawg@gmail.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "http://placeimg.com/640/480/animals"
}

### Sessions create (login)
GET {{ domain }}/sessions
Content-Type: application/json

{
  "email": "meghan@gmail.com",
  "password": "password"
}

###################################### USERS
### User index
GET {{ domain }}/users
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### User show
GET {{ domain }}/users/4
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### User update
PATCH {{ domain }}/users/4
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "first_name": "Meghan",
  "last_name": "Scherzer",
  "user_name": "meghan44",
  "email": "meghan@gmail.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "http://placeimg.com/640/480/people?t=1646424933414"
}

### User delete
DELETE {{ domain }}/users/4
Content-Type: application/json
Authorization: Bearer {{ jwt }}

################################### PRODUCTS
### Product index
GET {{ domain }}/products

### Product create
POST {{ domain }}/products
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "",
  "description": "",
  "category": "",
  "image_url": "",
  "price": ,
  "ingredients": ""
}

### Product show
GET {{ domain }}/products/4
Content-Type: application/json

### Product update
PATCH {{ domain }}/products/4
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": ""
}

### Product destroy
DELETE {{ domain }}/products/6
Content-Type: application/json

######################################### PRODUCT ALTERNATIVES
### ProductAlternatives create
POST {{ domain }}/product_alternatives
Content-Type: application/json

{
  "standard_product_id": "21",
  "green_product_id": "22"
}

### ProductAlternatives destroy
DELETE {{ domain }}/product_alternatives/2
Content-Type: application/json

######################################## REVIEWS
### Review index
GET {{ domain }}/reviews
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### Review create
POST {{ domain }}/reviews
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "product_id": 12,
  "title": "Best ever",
  "image_url": "",
  "body": "laksjdfasdfjhasldkfhaosiduf",
  "star_rating": 5
}

### Review show
GET {{ domain }}/reviews/1
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### Review update
PATCH {{ domain }}/reviews/3
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "image_url": "https://i5.walmartimages.com/asr/3c5910f8-4f34-4979-b014-b34e416c14ff_1.3f6241a35df3e30eb77a60d144a043a4.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF"
}

### Review destroy
DELETE {{ domain }}/reviews/4
Content-Type: application/json
Authorization: Bearer {{ jwt }}