# product = Product.new(
#   name: params[:name],
#   description: params[:description],
#   category: params[:category],
#   image_url: params[:image_url],
#   price: params[:price],
#   ingredients: params[:ingredients],
# )

# product = Product.create(name: "Clorox Disinfecting Wipes", description: "Clorox Disinfecting Wipes clean, disinfect and remove allergens for 5x cleaning power and leave a fresh Crisp Lemon scent. Disinfecting Wipes clean and disinfect with antibacterial power that kills 99.9% of viruses and bacteria that can live on surfaces, including COVID-19*Virus, staph, E. coli, MRSA, salmonella, strep and Kleb. These all-purpose disposable wipes remove common allergens, germs and messes on surfaces like kitchen counters, bathroom surfaces and more and can prevent the growth of bacteria* for up to 24 hours. Wipes are safe to use on finished wood, sealed granite and stainless steel. Disinfecting Wipes are also great on non-food-contact surfaces in the home, office, classroom, pet area, dorm and locker room. Clean with bleach-free wipes to keep dirt and germs away leaving behind a clean, Crisp Lemon scent. *Kills SARS-CoV-2 on hard, nonporous surfaces; *odor causing bacteria on non-food contact surfaces", category: "Standard", image_url: "https://www.clorox.com/wp-content/uploads/2020/12/194702.240_CDW_LBL_75ct_CrispLemon_ClearCap_20-10-20-1326.png", price: 4.48, ingredients: "ACTIVE INGREDIENTS: n-Alkyl (C14, 60%; C16, 30%; C12, 5%; C18, 5%) Dimethyl Benzyl Ammonium Chloride: 0.184%**; n-Alkyl (C12, 68%; C14, 32%) Dimethyl Ethylbenzyl Ammonium Chloride: 0.184%**")

# product = Product.create(name: "Windex Glass Cleaner", description: "Trusted by generations for an unbeatable streak-free shine**, Windex Original Glass Cleaner is a great solution for lightening and brightening your home. Relax and recharge by letting in all the feel-good power of natural light with Windex unbeatable streak-free window cleaner. It starts working on smudges, dirt, fingerprints and other messes even before you wipe. The recycled plastic bottle body is made of 100% Ocean Bound Plastic*, thanks to a partnership with Plastic Bank. This glass cleaner works great on windows, mirrors, glass and more. Enjoy 100% of the goodness that natural light brings with Windex Original Glass Cleaner. Light is Life. Let it all in. *Recyclable plastic bottle made of 100% Ocean Bound Plastic. Ocean Bound Plastic, in partnership with Plastic Bank, is post-consumer recycled plastic collected within 30 miles of an ocean or a waterway leading to an ocean, in countries with high volumes of uncollected plastic waste, which has been discarded or would otherwise be discarded into the environment.", category: "Standard", image_url: "https://i5.walmartimages.com/asr/9a682939-002f-4ed5-bef0-bf53f01e688b.74559e22ea3b2acc8ec6b1c3fe86fa43.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", price: 13.79, ingredients: "Water, Carriers, Cleaning Agents, Wetting Agent, Fragrance, Dye. SCJ Formula #35*14153")

# product = Product.create(name: "Dawn Dish Soap - 19.4oz", description: "Think all dish soaps are the same? Think again. No matter what you've got cooking in the kitchen, Dawn Ultra Original dishwashing liquid dish soap will leave your dishes squeaky clean every time. Get your ultimate clean and be the kitchen hero with the Grease Cleaning power of Dawn dishwashing liquid dish soap. With 50% less scrubbing* (*vs. Dawn Non-Concentrated), Dawn dishwashing liquid dish soap works harder so you can get back to spending quality time with your family. Dawn dishwashing liquid dish soap can even be used to clean items beyond the kitchen sink. Use Dawn dishwashing liquid to remove grease and grime from external car surfaces and the outer shroud of a gas grill. Dawn dishwashing liquid dish soap is tough on grease, yet gentle. It's so gentle that Dawn dishwashing liquid helps save rescued wildlife from oil spills. Dawn dishwashing liquid dish soap is Americas #1 Dish Liquid* (*based on sales).", category: "Standard", image_url: "https://i5.walmartimages.com/asr/e8cc4fdd-989b-4803-a943-217f6c9aefda.ecbe16686788e0684699fb707a75838c.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", price: 2.94, ingredients: "water, sodium lauryl sulfate, sodium laureth sulfate, lauramine oxide, sodium chloride, phenoxyethanol, PEI-14 PEG-10/PPG-7 copolymer, methylisothiazolinone, fragrance, yellow 5")

# product = Product.create(name: "All Purpose Cleaning Wipes, Lime + Sea Salt", description: "Put the hurt on dirt with Method's All Purpose Cleaning Wipes. Grease + grime don't stand a chance with these plant-based cleaning agents on your side. Each compostable* wipe packs a powerful cleaning punch, with cleansers derived from corn + coconut. They whisk away spills + splatters with ease, leaving behind the pleasant smell of victory. *Wipes will biodegrade under municipal composting conditions. Not suitable for backyard composting. Lime + Sea Salt — An elixir of sea salt + tart lime fragrance notes that practically puts the sand between your toes.", category: "Green", image_url: "https://d2eu6x79z4tb3o.cloudfront.net/products/13115/original/Method-Wipes-LimeSea-Single.jpg?1637271861", price: 7.99, ingredients: "water (aqua), decyl glucoside, cocamidopropyl betaine, phenoxyethanol, limonene, benzyl salicylate, lauryl glucoside, sodium gluconate, hydrated silica, potassium hydroxide, methylisothiazolinone, octylisothiazolinone")

# product = Product.create(name: "Biokleen Glass Cleaner Spray", description: "Our streak-free formula, with the cleaning power of vinegar and plant-based soil lifters, easily dissolves dirt, pollution, smoke and grease from shiny, hard surfaces. Naturally clean and clear!", category: "Green", image_url: "https://biokleenhome.com/media/catalog/product/cache/4ab856706ac6e1a24094d53eb58d3b5e/_/b/_b_0_b00080e.png", price: 9.99, ingredients: "water, limonene (plant-derived), sodium methyl 2-sulfolaurate (plant-derived), sodium citrate (plant-derived), acetic acid (plant-derived), isopropyl alcohol, C12-16 pareth-7 (plant-derived), lauryl glucoside (plant-derived), citrus grandis seed extract (plant-derived), phenoxyethanol, tetrasodium glutamate diacetate (plant-derived), and decyl glucoside.")

# product = Product.create(name: "Puracy Natural Dish Soap", description: "Puracy Dish Soap is a grease-cutting, skin-nourishing natural dishwashing liquid. These renewable and biodegradable ingredients were carefully chosen and developed into a premium solution that's plant-based, child-safe, pet-safe, hypoallergenic, and extremely effective.This concentrated formula requires only a teaspoon to do a sink full of dishes. Our dish soap is tough enough for pots and pans and gentle enough to wash your hands. ", category: "Green", image_url: "https://dyn.puracy.com/authority/19291069907040/hero.png?w=1000&h=1000", price: 5.99, ingredients: "Purified water (Aqua, eau), Lauryl/myristyl glucoside (Coconut-based cleanser), Cocamidopropyl hydroxysultaine (Coconut-based cleanser), Sodium lauroamphoacetate (Coconut-based cleanser), Lauramine oxide (Coconut-based cleanser), Sodium chloride (Natural salt), Vegetable glycerin (Plant-based skin softener), Benzisothiazolinone (Biodegradable preservative), Tetrasodium glutamate diacetate (Plant-based cleanser), Sodium lauroyl sarcosinate (Coconut oil-based cleanser), Natural fragrance, Citric acid (Plant-based pH neutralizer), Sodium citrate (Plant-based water softener), Himalayan pink sea salt, Aloe barbadensis (Aloe vera) leaf juice")
